version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/infrastructure"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/infrastructure"
    schedule:
      interval: "weekly"
