http:
  routers:
    to-tvheadend:
      entryPoints:
        - web
      rule: "Host(`${fqdn}`)"
      middlewares:
        - tvheadend-ipwhitelist
      service: tvheadend

  middlewares:
    tvheadend-ipwhitelist:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"
          - "192.168.0.0/16"
          - "10.0.0.0/8"

  services:
    tvheadend:
      loadBalancer:
        servers:
          - url: http://${host}:9981/

tcp:
  routers:
    to-tvheadend:
      entryPoints:
        - tvheadend_htsp
      rule: "HostSNI(`*`)"
      middlewares:
        - tvheadend-ipwhitelist
      service: tvheadend

  middlewares:
    tvheadend-ipwhitelist:
      ipWhiteList:
        sourceRange:
          - "192.168.0.0/16"

  services:
    tvheadend:
      loadBalancer:
        servers:
          - address: ${host}:9982