http:
  routers:
    to-calibre:
      entryPoints:
        - web
      rule: "Host(`${fqdn}`)"
      service: calibre

  services:
    calibre:
      loadBalancer:
        servers:
          - url: http://${host}:8083/