http:
  routers:
    to-gitea:
      entryPoints:
        - web
      rule: "Host(`${fqdn}`)"
      service: gitea

  services:
    gitea:
      loadBalancer:
        servers:
          - url: http://${host}:3000/

tcp:
  routers:
    to-gitea:
      entryPoints:
        - gitea_ssh
      rule: "HostSNI(`*`)"
      service: gitea

  services:
    gitea:
      loadBalancer:
        servers:
          - address: ${host}:22