http:
  routers:
    to-gitea:
      entryPoints:
        - web
      rule: "Host(`gitea.local`)"
      service: gitea

  services:
    gitea:
      loadBalancer:
        servers:
          - url: http://gitea:3000/

entryPoints:
  gitea:
    address: :2222

tcp:
  routers:
    to-gitea:
      entryPoints:
        - gitea_ssh
      rule: "HostSNI(`*`)"
      service: gitea

  services:
    gitea:
      loadBalancer:
        servers:
          - address: gitea:22