http:
  routers:
    to-gitea-insecure:
      entryPoints:
        - web
      rule: "Host(`${fqdn}`)"
      service: accidential_http
      middlewares:
        - https-redirect

    to-gitea-secure:
      entryPoints:
        - websecure
      rule: "Host(`${fqdn}`)"
      service: gitea
      middlewares:
        - secHeaders
        - https-redirect
      tls:
        certResolver: ${cert_resolver}

  services:
    gitea:
      loadBalancer:
        servers:
          - url: http://${host}:3000/

tcp:
  routers:
    to-gitea:
      entryPoints:
        - gitea_ssh
      rule: "HostSNI(`*`)"
      service: gitea

  services:
    gitea:
      loadBalancer:
        servers:
          - address: ${host}:22
