http:
  routers:
    to-tvheadend:
      entryPoints:
        - web
      rule: "Host(`${fqdn}`)"
      middlewares:
        - lan-whitelist
      service: backblaze

  services:
    backblaze:
      loadBalancer:
        servers:
          - url: http://${host}:8080/