http:
  routers:
    to-nginx:
      entryPoints:
        - web
      rule: "Host(`nginx.local`)"
      service: nginx
    to-nextcloud:
      entryPoints:
        - web
      rule: "Host(`nextcloud.local`)"
      service: nextcloud
    to-mailhog:
      entryPoints:
        - web
      rule: "PathPrefix(`/mail`)"
      middlewares:
        - mail-stripprefix
      service: mailhog

  middlewares:
    mail-stripprefix:
      stripPrefix:
        prefixes:
          - "/mail"

  services:
    nginx:
      loadBalancer:
        servers:
          - url: http://nginx/
    nextcloud:
      loadBalancer:
        servers:
          - url: http://nextcloud-app/
    mailhog:
      loadBalancer:
        servers:
          - url: http://mailhog:8025/