providers:
  file:
    directory: "/etc/traefik/hosts"

accessLog: {}

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and dashboard configuration
api:
  insecure: true

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

  %{ for name, port in additional_entrypoints }
  ${name}:
    address: ":${port}"
  %{ endfor ~}

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${email}
      storage: /acme/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web