providers:
  file:
    directory: "/etc/traefik/hosts"

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and dashboard configuration
api:
  insecure: true

entryPoints:
  web:
    address: :80
  %{ for name, port in additional_entrypoints }
  ${name}:
    address: ":${port}"
  %{ endfor ~}