providers:
  file:
    directory: "/etc/traefik/hosts"

accessLog: {}

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and dashboard configuration
api:
  insecure: true

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

  %{ for name, port in additional_entrypoints }
  ${name}:
    address: ":${port}"
  %{ endfor ~}

certificatesResolvers:
  %{ if homelab_ca == "" }
  letsencrypt:
    acme:
      email: ${email}
      storage: /acme/acme.json
      dnsChallenge:
        provider: cloudflare
  %{ else }
  homelab:
    acme:
      email: ${email}
      caServer: https://${homelab_ca}:9000/acme/acme/directory
      storage: /acme/acme_homelab.json
      tlsChallenge: {}
  %{ endif }