http:
  routers:
    to-nginx:
      entryPoints:
        - web
      rule: "Host(`${fqdn}`)"
      service: nginx

  services:
    nginx:
      loadBalancer:
        servers:
          - url: http://${host}/