#cloud-config
ssh_pwauth: True

hostname: backup

keyboard:
  layout: de
  model: pc105
  variant: nodeadkeys
  options: compose:rwin

users:
  - name: ${username}
    shell: /bin/bash
    passwd: ${password}
    # Enable password login
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    no_user_group: true
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDB6PprRBGhozT/8yYajVFoHWXfBUfa7ByyJig3OmA/thSeBjtotJ6H5spuaLhgmpRIekwNjEvL1B99aLj/rbpRnyHE8gHMBSN4OwNsfHBz6QhJnbdYaw1Fw751rpVhuua9/HL5mvsmNVfq7r0Vl0fBP6niucdh/j7vdMsE/2cHXMckJGBdnsV/IIgCel4GBmmYHpjwalUXvBW6e8Zdx4aPuXGhfWQvL+5ZI/Nr+G+m/pamBMFhyspmLnBSOBvO9jZgBtnxraQMNi55exWkt6UrjWThSX8DAYv7iCtcvKCwlvE8mo9WL2GqGYj6IQhnd6qncbG8yuuTFaQh84nVG+5x felix@felix-ThinkPad-E480
      
ssh_deletekeys: true
ssh_keys:
   dsa_private: |
      ${indent(6, dsa_private)}
   dsa_public: ${dsa_public}
   
   ecdsa_private: |
      ${indent(6, ecdsa_private)}
   ecdsa_public: ${ecdsa_public}
   
   ed25519_private: |
      ${indent(6, ed25519_private)}
   ed25519_public: ${ed25519_public}
   
   rsa_private: |
      ${indent(6, rsa_private)}
   rsa_public: ${rsa_public}
