tcp:
  routers:
    mailer:
      entryPoints:
        - "mailer"
      service: "mailer"
      rule: "HostSNI(`*`)"

  services:
    mailer:
      loadBalancer:
        servers:
          - address: "${host}:25"