http:
  routers:
    to-jellyfin:
      entryPoints:
        - web
      rule: "Host(`${fqdn}`)"
      middlewares:
        - lan-whitelist
      service: jellyfin

  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: http://${host}:8096/