http:
  routers:
    to-nextcloud:
      entryPoints:
        - web
      rule: "Host(`${fqdn}`)"
      service: nextcloud
      middlewares:
        - secHeaders
        - nextcloud-webdav
      tls:
        certResolver: letsencrypt

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: http://${host}/

  middlewares:
    nextcloud-webdav:
      replacePathRegex:
        regex: "^/.well-known/ca(l|rd)dav$"
        replacement: "/remote.php/dav/"