http:
  routers:
    to-nextcloud:
      entryPoints:
        - web
      rule: "Host(`${fqdn}`)"
      service: nextcloud
      tls:
        certResolver: letsencrypt

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: http://${host}/